### ISSUE TITLE
Error when try to run server

### ISSUE THREAD

**Issue by hichay** [york8817612/Ghost#22]
```
AM System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MySql.Data.MySqlClient.CharSetMap.GetCharacterSet(DBVersion version, String CharSetName)
   at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   at MySql.Data.MySqlClient.MySqlField.SetTypeAndFlags(MySqlDbType type, ColumnFlags flags)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   at MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   at MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   at MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.Close()
   at MySql.Data.MySqlClient.MySqlConnection.Close()
   at MySql.Data.MySqlClient.MySqlHelper.ExecuteReader(String connectionString, String commandText, MySqlParameter[] commandParameters)
   at MySql.Data.MySqlClient.MySqlHelper.ExecuteReader(String connectionString, String commandText)
   at Server.Common.Data.Datums.PopulateInternal(String fields, String constraints) in D:\Ghostsv\Server (1)\Ghost-master\Server\Common\Data\Datum.cs:line 26
   at Server.Common.Data.Datums.Populate() in D:\Ghostsv\Server (1)\Ghost-master\Server\Common\Data\Datum.cs:line 64
   at Server.Ghost.Provider.MobFactory.InitializeMonsterDrop() in D:\Ghostsv\Server (1)\Ghost-master\Server\GameServer\Ghost\Provider\MobFactory.cs:line 1819
   at Server.GameServer.Main(String[] args) in D:\Ghostsv\Server (1)\Ghost-master\Server\GameServer\GameServer.cs:line 128
```

**Comment by unbrall301** [comment]
wrong version mysql，you should use the 5.6.17
